### ISSUE TITLE
provide graceful IP-to-user mapping configuration to allow 'root' access in VM

### ISSUE THREAD

**Issue by JackJHarris** [irods/irods_client_nfsrods#130]
# What

Squash all remote R/W access from a given IP to a single definable user
(e.g., export /p to 10.0.1.2 as user1; export /p  to 10.0.1.3 as user2, ...)
But, also have a way to update the mappings without restarting the NFS daemon and affecting existing connections.

# Why

Without this  giving sudo access to a user hosts on remote ephemeral systems; -- they essentially  can then become any user on the remote file system as well unless the NFS server is setup to squash the user 

We would like to tell iRods that a node is mapped to a user during our node initialization process to lock this access down but still allow users to have sudo rights.

# How (options)

- endpoint for updating the IP to user mapping
- update the config and iRods can `stat` the file and update from it if it was modified from its last known date time stamp
- signal sent to the process to re-read a configfile 

# Options
IP ranges or lists would be nice -- but not required for this
e.g.,
10.0.1.2, 10.0.1.22, 10.2.0.0/24, 10.3.0.1-10.3.0.10 user1

**Comment by trel** [comment]
A few questions to ponder...

- What happens when a specified IP or range overlaps with or is double-defined with another range?  Feels like on server startup, it should halt (aka not start), and for re-loading, it should ignore the new config and yell in the log.
- Upon re-loading the configuration/mappings... will need to be careful to have existing connections 'do the right thing' in case their current/existing IP is one that was re-mapped.  Definitely some tests for this need to be defined/written.
- What happens when the user being mapped-to does not exist?
- What happens when the config is malformed (bad IP, bad range, etc.)
- Presumably, many-IP-to-one-user is a valid configuration
- Presumably, one-IP-to-many-user is not (see above about overlapping ranges)
- Should this entire 'mode' be turned on by the presence of the config stanza?  Or an explicit knob itself?   Leaning to 'stanza-is-defined' is sufficient and clear.  Need to name this 'mode'...

**Comment by JackJHarris** [comment]
1. yep
2. config validation fails, nothing is reloaded -- but communicating this failed state back is the trick...hmm.
3. agreed
4. same as item 2
5. same as item 2
6. I'm ok with whatever

Seems like you hit on an issue regarding how to communicate the (attempted) updated status from the server to the client -- if this is done asyncronously, how does the calling process know what happened? 

For example: If the iRods NFS daemon monitors config files (as initially suggested) then it is up to the updating process to monitor log files  to get the status of the attempted change -- similar to if an admin made config file changes manually

However, if there was an end point or client that could be called -- "update-config" that would initiate the reprocessing of the config (similar to "exportfs") then that process could simply respond with exit codes and output on stderr regarding what happened

**Comment by trel** [comment]
regarding the re-load...  Yes, we were thinking a more explicit endpoint is probably the most flexible answer - it's synchronous and can report back, as you say... and of course, we still have the logging for posterity/timestamps.

should the endpoint require a shared token to activate/use... defined in the existing config?  hmmm, seems circular...   would/could help against DoS... maybe not worth it...  maybe a 'wait and see if we need it' issue to be filed...

**Comment by trel** [comment]
We do not intend to implement this request.

NFS can do this already...

> This can be accomplished by setting the following options on an export entry in `/etc/exports`:
> 
> - Add `all_squash` to the list of export options
> - Set the export options, `anonuid` and `anongid`, to the target UID and GID respectively
> 
> Information obtained using the following sources:
> 
> - `man 5 exports`
>     - See section entitled **User ID Mapping**
> - https://serverfault.com/questions/539267/nfs-share-with-root-for-anonuid-anongid/615624#615624
