### ISSUE TITLE
Investigate inconsistencies in tests

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_nfsrods#187]
**create, list, rename, copy, move, and remove file** should be (to account for linux vs macOS)
```bats
# error code 1 on mac, error code 2 on linux
[ ! $status -eq 0 ]
# [[ "${output}" == *"ls: cannot access"* ]] # this line doesn't hold true on mac
[[ "${output}" == *"${FILENAME}"* ]]
[[ "${output}" == *"No such file or directory"* ]]
```

**failing on linux, but not on macOS** (on `46.main.restart` branch)
- listing directory with large number of entries prints all entries
- rename directory

**ocasionally failing on macOS** (on `main`), but can't re-produce. it's happened once or twice out of all the times I've ran these tests
- move file into directory

**Comment by korydraughn** [comment]
I don't think we even need to detect the difference between the OSs.

The test only needs to confirm that a non-zero error code is returned and the common part of the error message exists. Essentially, what's already reported in the BATs sample.

**Comment by trel** [comment]
that's fair - if we just want to assert non-zero.

**Comment by korydraughn** [comment]
I think this may be due to the BATS (the test framework) rather than NFSRODS. For example:
- Running the tests, `rename file` and `rename directory` together results in `rename directory` failing
- Running `rename directory` by itself results in it succeeding
- Passing the current directory to `/bin/ls` in the `rename directory` test results in the test passing in either of the cases previously mentioned

Executing the commands manually succeed too, so this makes me think we may have written a bad test.

**Comment by korydraughn** [comment]
This situation turned out to NOT be BATS.

This was an actual bug in the implementation where we weren't clearing some caches at the correct moments.

With the recent commits, the tests pass consistently.

**Comment by trel** [comment]
Wild.    Thanks tests!
